name: CICD
on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # 拉取最新的代码
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      # 安装 Node.js 环境
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      # 安装依赖
      - name: Installing Dependencies
        run: npm install --legacy-peer-deps

      # 打包
      - name: Build
        run: npm run build

      # 列出 dist 目录中的文件，确保构建成功并有产物
      - name: List dist directory
        run: ls -l dist/

      # 上传到目标服务器
      - name: Upload to Deploy Server@root
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          SOURCE: "dist/"
          ARGS: "-avzr --delete"
          TARGET: "/www/rpworld_hr"
          # 确保使用 SSH 进行连接
          RSYNC_SSH_COMMAND: "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -v"
